# Generated by Django 3.2.9 on 2022-10-20 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docCancel', models.CharField(max_length=120)),
                ('url', models.CharField(default='/', max_length=100)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Motivo_cancelacion_sat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.PositiveIntegerField()),
                ('valor', models.CharField(default=None, max_length=120)),
            ],
            options={
                'verbose_name': 'Clave',
                'verbose_name_plural': 'Claves',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(default=None, max_length=120)),
                ('cartera_cliente', models.CharField(default=None, max_length=8)),
                ('folio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rfc', models.CharField(max_length=14)),
                ('UUID', models.CharField(max_length=36)),
                ('motivo_de_cancelacion', models.CharField(max_length=60)),
                ('fecha_sol_de_cancelacion', models.DateField(default=django.utils.timezone.now)),
                ('solicitante', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='NotaCargo',
            fields=[
                ('solicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_factura.solicitud')),
                ('cuenta_contable', models.CharField(max_length=12, null=True)),
                ('documento', models.FileField(max_length=120, upload_to='media/nota_cargo/%d-%m-%Y')),
                ('obs', models.CharField(default='', max_length=600)),
            ],
            options={
                'verbose_name': 'Solicitud de nota de cargo',
                'verbose_name_plural': 'Solicitudes de nota de cargo',
            },
            bases=('app_factura.solicitud',),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('solicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_factura.solicitud')),
                ('inv', models.PositiveIntegerField()),
                ('suplementaria', models.BooleanField()),
                ('obs', models.CharField(default='', max_length=600)),
            ],
            options={
                'verbose_name': 'CFDI de vehiculo',
                'verbose_name_plural': 'CFDI de vehiculos',
            },
            bases=('app_factura.solicitud',),
        ),
        migrations.CreateModel(
            name='Solicitud_atendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fecha_de_cancelacion', models.DateField(default=django.utils.timezone.now)),
                ('estatus', models.CharField(max_length=40)),
                ('comentarios', models.CharField(default='', max_length=120, null=True)),
                ('atendida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_factura.solicitud')),
                ('userCancel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud atendida',
                'verbose_name_plural': 'Atendidas',
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_factura.sucursal'),
        ),
        migrations.CreateModel(
            name='Vehiculo_seminuevo',
            fields=[
                ('solicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_factura.solicitud')),
                ('inv', models.PositiveIntegerField()),
                ('obs', models.CharField(default='', max_length=600)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_factura.documento')),
            ],
            options={
                'verbose_name': 'CFDI de vehiculo usado',
                'verbose_name_plural': 'CFDI de vehiculos usdos',
            },
            bases=('app_factura.solicitud',),
        ),
    ]
