# Generated by Django 3.2.9 on 2022-10-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacargo',
            name='archivo',
            field=models.FileField(default='media/nota_cargo/19-10-2022/20_SL_ASSLCLIDN_4282.pdf', max_length=120, upload_to='media/nota_cargo/%d-%m-%Y'),
        ),
        migrations.AlterField(
            model_name='notacargo',
            name='documento',
            field=models.CharField(default='Nota de cargo', max_length=30),
        ),
    ]
