# Generated by Django 3.2.9 on 2022-10-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0002_auto_20221019_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacargo',
            name='archivo',
            field=models.FileField(max_length=120, upload_to='media/nota_cargo/%d-%m-%Y'),
        ),
    ]
