# Generated by Django 3.2.9 on 2021-11-17 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0004_solicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_factura.sucursal'),
        ),
    ]
