# Generated by Django 3.2.9 on 2021-11-17 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0005_auto_20211117_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_factura.sucursal'),
        ),
    ]
