# Generated by Django 3.2.9 on 2022-10-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0006_auto_20221020_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo_seminuevo',
            options={'verbose_name': 'Vehiculo seminuevo', 'verbose_name_plural': 'Solicidudes de vehiculos seminuevos'},
        ),
        migrations.AlterField(
            model_name='vehiculo_seminuevo',
            name='documento',
            field=models.CharField(default='Factura de vehiculo seminuevo', max_length=30),
        ),
    ]
