# Generated by Django 3.2.9 on 2022-10-21 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0007_auto_20221020_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_sol_de_cancelacion',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
