# Generated by Django 3.2.9 on 2022-10-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0008_alter_solicitud_fecha_sol_de_cancelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo_seminuevo',
            name='archivo',
            field=models.FileField(max_length=130, upload_to='media/vehiculo/seminuevo/%d-%m-%Y'),
        ),
    ]
