# Generated by Django 3.2.9 on 2021-11-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0008_alter_solicitud_solicito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud_atendida',
            old_name='obs',
            new_name='comentarios',
        ),
    ]
