# Generated by Django 3.2.9 on 2021-11-21 02:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0009_rename_obs_solicitud_atendida_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_atendida',
            name='atendida',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_factura.solicitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud_atendida',
            name='fecha_de_cancelacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
