# Generated by Django 3.2.9 on 2022-01-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0013_solicitud_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='area',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='uid',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cartera_cliente',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cuenta_contable',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre_cliente',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='folio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
