# Generated by Django 3.2.9 on 2022-01-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0014_auto_20220104_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo_cancelacion_sat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.PositiveIntegerField()),
                ('valor', models.CharField(default=None, max_length=120)),
            ],
            options={
                'verbose_name': 'Clave',
                'verbose_name_plural': 'Claves',
            },
        ),
        migrations.AddField(
            model_name='solicitud_atendida',
            name='motivo_cancelacion_sat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_factura.motivo_cancelacion_sat'),
        ),
    ]
