# Generated by Django 4.0.4 on 2022-04-22 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0015_auto_20220105_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_atendida',
            name='motivo_cancelacion_sat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_factura.motivo_cancelacion_sat'),
        ),
    ]
