# Generated by Django 4.0.4 on 2022-04-28 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0017_alter_solicitud_fecha_sol_de_cancelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_atendida',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitud_atendida',
            name='fecha_de_cancelacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
