# Generated by Django 4.0.4 on 2022-04-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_factura', '0019_alter_solicitud_atendida_fecha_de_cancelacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_atendida',
            name='motivo_cancelacion_sat',
        ),
    ]
