# Generated by Django 3.2.9 on 2022-10-28 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_factura', '0009_alter_vehiculo_seminuevo_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=80)),
                ('año', models.PositiveSmallIntegerField()),
                ('placa', models.CharField(help_text='Coloca la placa sin guiones ni espacios', max_length=7)),
                ('entidad', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=17)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vheículos',
            },
        ),
        migrations.CreateModel(
            name='Sucursal_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Usuario_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Pagos_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenencia', models.DateField()),
                ('costo_tenencia', models.DecimalField(decimal_places=2, max_digits=20)),
                ('verificacion', models.DateField()),
                ('refrendo', models.DateField()),
                ('tarjeta_circulacion', models.DateField()),
                ('seguro', models.DateField(default=None, null=True)),
                ('costo_seguro', models.DecimalField(decimal_places=2, default=None, max_digits=30)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_administracion.administracion_vehiculo')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_factura.sucursal')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
            },
        ),
        migrations.AddField(
            model_name='administracion_vehiculo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_administracion.sucursal_vehiculo'),
        ),
        migrations.AddField(
            model_name='administracion_vehiculo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_administracion.usuario_vehiculo'),
        ),
    ]
