# Generated by Django 3.2.9 on 2022-10-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administracion_vehiculo',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vheículo'},
        ),
    ]
