# Generated by Django 3.2.9 on 2022-10-28 04:11
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_administracion', '0002_alter_administracion_vehiculo_options'),
    ]

    operations = [
migrations.CreateModel(
            name='Pagos_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenencia', models.DateField()),
                ('costo_tenencia', models.DecimalField(decimal_places=2, max_digits=20)),
                ('verificacion', models.DateField()),
                ('refrendo', models.DateField()),
                ('tarjeta_circulacion', models.DateField()),
                ('seguro', models.DateField(default=None, null=True)),
                ('costo_seguro', models.DecimalField(decimal_places=2, default=None, max_digits=30)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Sucursal_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Usuario_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
