# Generated by Django 3.2.9 on 2022-10-28 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_administracion', '0003_delete_chofer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=180)),
                ('placa', models.CharField(max_length=13)),
                ('vin', models.CharField(max_length=17)),
                ('propietario', models.CharField(default='Sin propietario', max_length=180)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vheículos',
            },
        ),
    ]
