# Generated by Django 3.2.9 on 2022-10-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_administracion', '0005_auto_20221027_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal_vehiculo',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RenameField(
            model_name='sucursal_vehiculo',
            old_name='sucursal',
            new_name='empresa',
        ),
    ]
