# Generated by Django 3.2.9 on 2022-10-28 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_administracion', '0006_auto_20221027_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sucursal_vehiculo',
            new_name='Empresa_vehiculo',
        ),
    ]
