# Generated by Django 3.2.9 on 2022-10-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_administracion', '0007_rename_sucursal_vehiculo_empresa_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
    ]
